// saflash — B2 phrases. Row format: [phrase_en, phrase_es, category, context|null]

export const B2_PHRASES = [
  ["I was wondering if you could help me","Me preguntaba si podrías ayudarme","courtesy","Very polite request"],
  ["Would it be possible to...?","¿Sería posible...?","courtesy","Polite request"],
  ["I'd appreciate it if you could...","Agradecería que pudieras...","courtesy","Formal polite request"],
  ["I hope I'm not interrupting","Espero no interrumpir","courtesy","When approaching someone busy"],
  ["Thank you for your patience","Gracias por su paciencia","courtesy","When someone has waited"],
  ["I owe you one","Te debo una","courtesy","After someone does you a favor"],
  ["To be honest","Para ser sincero","social","Before giving a frank opinion"],
  ["It's not that I mind, but...","No es que me moleste, pero...","social","Softening a complaint"],
  ["If you ask me...","Si me preguntas...","social","Before giving your opinion"],
  ["As far as I'm concerned","En lo que a mí respecta","social","Stating your own view"],
  ["I see your point, but...","Entiendo tu punto, pero...","social","Politely disagreeing"],
  ["I'm not so sure about that","No estoy tan seguro de eso","social","Expressing doubt politely"],
  ["That's easier said than done","Es más fácil decirlo que hacerlo","social","When something is hard to do"],
  ["Don't get me wrong","No me malinterpretes","social","Before clarifying your intention"],
  ["It's up in the air","Todavía no está decidido","social","When a plan is not settled"],
  ["Let's agree to disagree","Quedemos en que no estamos de acuerdo","social","Ending a debate politely"],
  ["I couldn't care less","No me importa en absoluto","social","When you are totally indifferent"],
  ["It slipped my mind","Se me pasó","social","When you forgot something"],
  ["I'll sleep on it","Lo consultaré con la almohada","social","When you need time to decide"],
  ["I'm all ears","Soy todo oídos","social","When inviting someone to speak"],
  ["Long story short","Resumiendo","social","Before summarizing"],
  ["Speak of the devil!","¡Hablando del rey de Roma!","social","When the person you mention arrives"],
  ["That rings a bell","Eso me suena","social","When something seems familiar"],
  ["I'm not following you","No te estoy siguiendo","questions","When you are lost in an explanation"],
  ["Could you elaborate on that?","¿Podrías explicar eso con más detalle?","questions","Asking for more information"],
  ["What exactly do you mean by that?","¿Qué quieres decir exactamente?","questions","Asking for clarification"],
  ["Do you happen to know...?","¿No sabrás por casualidad...?","questions","Polite indirect question"],
  ["Is it okay if I join you?","¿Te parece bien si me uno?","questions","Asking to join a group"],
  ["Do you have a minute?","¿Tienes un minuto?","questions","Asking for someone's time"],
  ["Let's touch base tomorrow","Hablemos mañana para ver cómo va","work","When proposing a follow-up"],
  ["I need to run this by my manager","Tengo que consultarlo con mi jefe","work","When needing approval"],
  ["Let's circle back to that later","Volvamos a eso más tarde","work","When postponing a discussion"],
  ["Can I pick your brain?","¿Puedo consultarte algo?","work","When asking for someone's advice"],
  ["I'll look into it","Voy a investigarlo","work","When promising to check something"],
  ["Let's take this offline","Hablemos de esto aparte","work","When moving a topic out of a meeting"],
  ["I'm in charge of the project","Estoy a cargo del proyecto","work","Describing your responsibility"],
  ["We're running behind schedule","Vamos atrasados","work","When a project is late"],
  ["Let's get the ball rolling","Pongamos manos a la obra","work","When starting a task"],
  ["I'll take it from here","Yo me encargo desde aquí","work","When taking over a task"],
  ["Please bear with me","Por favor, tenga paciencia conmigo","work","When asking for patience"],
  ["I'm fed up","Estoy harto","emotions","When expressing frustration"],
  ["I'm heartbroken","Tengo el corazón roto","emotions","When expressing deep sadness"],
  ["I'm over the moon!","¡Estoy feliz de la vida!","emotions","When expressing extreme happiness"],
  ["I'm on edge","Estoy con los nervios de punta","emotions","When feeling tense"],
  ["I'm drained","Estoy agotado","emotions","When exhausted physically or mentally"],
  ["That really got to me","Eso me afectó mucho","emotions","When something upset you"],
  ["I'm at my wit's end","Ya no sé qué hacer","emotions","When you have run out of patience or options"],
  ["Spill the beans","Suelta la sopa","idioms","Asking someone to reveal a secret"],
  ["It's a blessing in disguise","No hay mal que por bien no venga","idioms","When bad luck turns out well"],
  ["We're on the same page","Estamos de acuerdo","idioms","When you share understanding"],
  ["The ball is in your court","Te toca a ti decidir","idioms","When someone else must act"],
  ["Out of the blue","De la nada","idioms","When something is unexpected"],
  ["Back to square one","Volver a empezar","idioms","When progress is lost"],
  ["Beat around the bush","Andarse con rodeos","idioms","When avoiding the main point"],
  ["In the long run","A la larga","idioms","When talking about final results"],
  ["That's the last straw","Esto es la gota que colmó el vaso","idioms","When patience runs out"],
  ["Go the extra mile","Esforzarse más de lo esperado","idioms","When doing more than required"],
  ["You're pulling my leg","Me estás tomando el pelo","idioms","When you think someone is joking"],
  ["Hit the nail on the head","Dar en el clavo","idioms","When someone is exactly right"],
  ["Jump the gun","Adelantarse","idioms","When acting too early"],
  ["Take it with a grain of salt","Tómalo con pinzas","idioms","When you doubt something"],
  ["Burn the midnight oil","Trasnochar trabajando","idioms","When working late at night"],
  ["The roads are icy","Las calles están heladas","weather","When warning about a condition"],
  ["It hailed last night","Cayó granizo anoche","weather","When recounting a weather event"],
  ["The forecast calls for heavy rain","El pronóstico anuncia lluvias fuertes","weather","When reading the forecast"],
  ["We were caught in the rain","Nos sorprendió la lluvia","weather","When getting wet unexpectedly"],
  ["Do I need stitches?","¿Necesito puntos?","health","When assessing a wound"],
  ["I've been feeling run down lately","Me he sentido sin energía últimamente","health","Describing low energy"],
  ["I need a second opinion","Necesito una segunda opinión","health","When doubting a diagnosis"],
  ["The pain comes and goes","El dolor va y viene","health","Describing symptoms"],
  ["We adopted a child","Adoptamos a un niño","family","When recounting a family event"],
  ["We're a close-knit family","Somos una familia muy unida","family","Describing family closeness"],
  ["She was raised by her grandparents","La criaron sus abuelos","family","Talking about someone's upbringing"],
  ["He's the black sheep of the family","Es la oveja negra de la familia","family","Describing the odd one out"],
];
