// saflash — C1 phrases. Row format: [phrase_en, phrase_es, category, context|null]

export const C1_PHRASES = [
  ["By and large","En general / Por lo general","social","Summarizing a broad truth"],
  ["It goes without saying","Ni qué decir tiene","social","When something is obvious"],
  ["I couldn't agree more","No podría estar más de acuerdo","social","Strong agreement"],
  ["Be that as it may","Sea como sea / Aun así","social","Conceding a point before continuing"],
  ["For what it's worth","Por si sirve de algo","social","Offering an opinion modestly"],
  ["To a certain extent","Hasta cierto punto","social","Partial agreement"],
  ["On the contrary","Al contrario","social","Strongly contradicting"],
  ["Needless to say","Huelga decir","social","Introducing an obvious fact"],
  ["As a matter of fact","De hecho","social","Adding a surprising fact"],
  ["Having said that","Dicho esto","social","Introducing a contrast"],
  ["All things considered","Considerándolo todo","social","Before concluding"],
  ["That's a fair point","Es una observación válida","social","Acknowledging an argument"],
  ["I beg to differ","Permítame discrepar","social","Formal disagreement"],
  ["If I may say so","Si me permite decirlo","social","Introducing a bold remark"],
  ["I stand corrected","Me han corregido, tienen razón","social","Admitting a mistake"],
  ["It remains to be seen","Está por verse","social","When the outcome is uncertain"],
  ["It's a matter of opinion","Es cuestión de opiniones","social","When there is no single answer"],
  ["Speaking from experience","Hablando por experiencia","social","Backing up your claim"],
  ["Nothing could be further from the truth","Nada más lejos de la verdad","social","Strongly rejecting a claim"],
  ["With all due respect","Con el debido respeto","courtesy","Before disagreeing politely"],
  ["I would be most grateful if you could...","Le estaría muy agradecido si pudiera...","courtesy","Formal request"],
  ["Please accept my sincere apologies","Le ruego acepte mis más sinceras disculpas","courtesy","Formal apology"],
  ["I regret to inform you that...","Lamento informarle que...","courtesy","Delivering bad news formally"],
  ["Allow me to express my gratitude","Permítame expresar mi gratitud","courtesy","Formal thanks"],
  ["I trust this finds you well","Espero que se encuentre bien","courtesy","Opening of a formal email"],
  ["Should you have any questions, please do not hesitate to contact me","Si tiene alguna duda, no dude en contactarme","courtesy","Closing of a formal email"],
  ["I look forward to hearing from you","Quedo a la espera de su respuesta","courtesy","Closing of a formal email"],
  ["We have reached a consensus","Hemos llegado a un consenso","work","Reporting an agreement"],
  ["It's in our best interest to...","Es lo mejor para nosotros...","work","Defending a decision"],
  ["I'd like to draw your attention to...","Quisiera llamar su atención sobre...","work","In presentations"],
  ["Let's not lose sight of the bigger picture","No perdamos de vista el panorama general","work","Refocusing a discussion"],
  ["We need to weigh the pros and cons","Debemos sopesar pros y contras","work","Before deciding"],
  ["The deadline is non-negotiable","El plazo no es negociable","work","Firm statement"],
  ["I'll go over the figures with you","Revisaré las cifras contigo","work","Offering to explain data"],
  ["That falls outside my remit","Eso queda fuera de mi competencia","work","Declining responsibility"],
  ["We're stretched thin","Tenemos los recursos al límite","work","When the team is overloaded"],
  ["It's a double-edged sword","Es un arma de doble filo","idioms","When something has pros and cons"],
  ["Read between the lines","Leer entre líneas","idioms","Understanding hidden meaning"],
  ["The elephant in the room","El tema incómodo que todos evitan","idioms","An obvious problem nobody mentions"],
  ["Add insult to injury","Echar sal en la herida","idioms","Making a bad situation worse"],
  ["Throw in the towel","Tirar la toalla","idioms","Giving up"],
  ["The tip of the iceberg","La punta del iceberg","idioms","A small visible part of a bigger problem"],
  ["Bite off more than you can chew","Abarcar más de lo que se puede","idioms","Taking on too much"],
  ["The writing is on the wall","Se veía venir","idioms","When failure is clearly coming"],
  ["Turn a blind eye","Hacer la vista gorda","idioms","Ignoring something on purpose"],
  ["Go back to the drawing board","Volver a empezar desde cero","idioms","Starting a plan again"],
  ["Pull strings","Mover hilos / Tener contactos","idioms","Using influence"],
  ["A drop in the ocean","Una gota en el océano","idioms","Something too small to matter"],
  ["Steal the show","Robarse el show","idioms","Being the center of attention"],
  ["Get cold feet","Echarse para atrás","idioms","Becoming nervous before a commitment"],
  ["I'm swamped with obligations","Estoy abrumado de obligaciones","emotions","Describing overload"],
  ["I'm utterly exhausted","Estoy completamente agotado","emotions","Extreme tiredness"],
  ["It was a bittersweet moment","Fue un momento agridulce","emotions","Mixed feelings"],
  ["I'm deeply moved","Estoy profundamente conmovido","emotions","Strong emotion"],
  ["I'm at a loss for words","No encuentro las palabras","emotions","When speechless"],
];
