// saflash — B1 words. Row format: [english, spanish, category, subcategory|null]

export const B1_WORDS = [
  ["include","incluir","other",null],
  ["continue","continuar","verbs_action",null],
  ["lead","liderar/guiar","verbs_action",null],
  ["create","crear","verbs_action",null],
  ["allow","permitir","verbs_action",null],
  ["offer","ofrecer","verbs_action",null],
  ["consider","considerar","other",null],
  ["appear","aparecer","other",null],
  ["expect","esperar/suponer","other",null],
  ["reach","alcanzar/llegar","verbs_action",null],
  ["remain","permanecer","other",null],
  ["suggest","sugerir","other",null],
  ["raise","levantar/aumentar","verbs_action",null],
  ["require","requerir","other",null],
  ["report","informar/reportar","other",null],
  ["whisper","susurrar","verbs_action",null],
  ["lend","prestar","verbs_action",null],
  ["steal","robar","verbs_action",null],
  ["earn","ganar (dinero)","verbs_action",null],
  ["choose","elegir","verbs_action",null],
  ["organize","organizar","verbs_action",null],
  ["imagine","imaginar","verbs_action",null],
  ["promise","prometer","verbs_action",null],
  ["describe","describir","verbs_action",null],
  ["compare","comparar","other",null],
  ["disagree","no estar de acuerdo","other",null],
  ["accept","aceptar","other",null],
  ["refuse","rechazar","other",null],
  ["bother","molestar","other",null],
  ["depend","depender","other",null],
  ["belong","pertenecer","other",null],
  ["contain","contener","other",null],
  ["exist","existir","other",null],
  ["produce","producir","other",null],
  ["develop","desarrollar","other",null],
  ["support","apoyar/soportar","other",null],
  ["protect","proteger","other",null],
  ["prevent","prevenir/evitar","other",null],
  ["avoid","evitar","other",null],
  ["cause","causar","other",null],
  ["affect","afectar","other",null],
  ["increase","aumentar","other",null],
  ["reduce","reducir","other",null],
  ["improve","mejorar","other",null],
  ["achieve","lograr","other",null],
  ["determine","determinar","other",null],
  ["identify","identificar","other",null],
  ["recognize","reconocer","other",null],
  ["introduce","presentar/introducir","other",null],
  ["mention","mencionar","other",null],
  ["claim","afirmar/reclamar","other",null],
  ["prove","probar/demostrar","other",null],
  ["confirm","confirmar","other",null],
  ["deny","negar","other",null],
  ["argue","discutir/argumentar","other",null],
  ["discuss","discutir/debatir","other",null],
  ["express","expresar","other",null],
  ["complain","quejarse","other",null],
  ["warn","advertir","other",null],
  ["encourage","animar/alentar","other",null],
  ["convince","convencer","other",null],
  ["force","forzar/obligar","other",null],
  ["common","común","adjectives",null],
  ["rare","raro/poco común","adjectives",null],
  ["necessary","necesario","adjectives",null],
  ["available","disponible","adjectives",null],
  ["similar","similar/parecido","adjectives",null],
  ["complex","complejo","adjectives",null],
  ["exciting","emocionante","adjectives",null],
  ["awful","horrible","adjectives",null],
  ["pleasant","agradable","adjectives",null],
  ["unpleasant","desagradable","adjectives",null],
  ["uncomfortable","incómodo","adjectives",null],
  ["cruel","cruel","adjectives",null],
  ["brave","valiente","adjectives",null],
  ["proud","orgulloso","adjectives",null],
  ["ashamed","avergonzado","adjectives",null],
  ["jealous","celoso","adjectives",null],
  ["curious","curioso","adjectives",null],
  ["confident","seguro de sí mismo","adjectives",null],
  ["faucet","grifo/canilla","home",null],
  ["rug","alfombra pequeña","home",null],
  ["nephew","sobrino","family",null],
  ["niece","sobrina","family",null],
  ["twin","gemelo/mellizo","family",null],
  ["partner","pareja/compañero","family",null],
  ["marriage","matrimonio","family",null],
  ["muscle","músculo","body",null],
  ["lung","pulmón","body",null],
  ["liver","hígado","body",null],
  ["kidney","riñón","body",null],
  ["eyebrow","ceja","body",null],
  ["patient","paciente","health",null],
  ["surgery","cirugía","health",null],
  ["emergency","emergencia","health",null],
  ["ambulance","ambulancia","health",null],
  ["injury","lesión/herida","health",null],
  ["wound","herida","health",null],
  ["virus","virus","health",null],
  ["infection","infección","health",null],
  ["vaccine","vacuna","health",null],
  ["allergy","alergia","health",null],
  ["prescription","receta médica","health",null],
  ["treatment","tratamiento","health",null],
  ["recovery","recuperación","health",null],
  ["blood pressure","presión arterial","health",null],
  ["symptom","síntoma","health",null],
  ["diagnosis","diagnóstico","health",null],
  ["operation","operación","health",null],
  ["wheelchair","silla de ruedas","health",null],
  ["bandage","vendaje/venda","health",null],
  ["syringe","jeringa","health",null],
  ["X-ray","radiografía","health",null],
  ["therapy","terapia","health",null],
  ["mental health","salud mental","health",null],
  ["toothache","dolor de muelas","health",null],
  ["flour","harina","food_drink","grains"],
  ["uniform","uniforme","clothing",null],
  ["zipper","cierre/cremallera","clothing",null],
  ["silk","seda","clothing",null],
  ["thunder","trueno","nature",null],
  ["lightning","relámpago/rayo","nature",null],
  ["soil","suelo/tierra","nature",null],
  ["cave","cueva/caverna","nature",null],
  ["volcano","volcán","nature",null],
  ["earthquake","terremoto/sismo","nature",null],
  ["flood","inundación","nature",null],
  ["sunrise","amanecer/salida del sol","nature",null],
  ["wolf","lobo","animals","wild"],
  ["fox","zorro","animals","wild"],
  ["deer","ciervo/venado","animals","wild"],
  ["gorilla","gorila","animals","wild"],
  ["dolphin","delfín","animals","sea"],
  ["eagle","águila","animals","birds"],
  ["parrot","loro","animals","birds"],
  ["software","software/programa","technology",null],
  ["hardware","hardware","technology",null],
  ["data","datos","technology",null],
  ["upload","subir/cargar","technology",null],
  ["network","red","technology",null],
  ["Bluetooth","Bluetooth","technology",null],
  ["robot","robot","technology",null],
  ["search engine","buscador","technology",null],
  ["social media","redes sociales","technology",null],
  ["helicopter","helicóptero","transport",null],
  ["ferry","ferry/transbordador","transport",null],
  ["highway","autopista","transport",null],
  ["tunnel","túnel","transport",null],
  ["engine","motor","transport",null],
  ["degree","título/grado","education",null],
  ["laboratory","laboratorio","education",null],
  ["science","ciencia","education",null],
  ["semester","semestre","education",null],
  ["scholarship","beca","education",null],
  ["graduation","graduación","education",null],
  ["golf","golf","sports",null],
  ["trophy","trofeo","sports",null],
  ["stadium","estadio","sports",null],
  ["competition","competencia/competición","sports",null],
  ["tournament","torneo","sports",null],
  ["Olympics","Juegos Olímpicos","sports",null],
  ["racket","raqueta","sports",null],
  ["anger","enojo/ira","emotions",null],
  ["joy","alegría","emotions",null],
  ["sadness","tristeza","emotions",null],
  ["disgust","asco/repulsión","emotions",null],
  ["trust","confianza","emotions",null],
  ["jealousy","celos/envidia","emotions",null],
  ["regret","arrepentimiento","emotions",null],
  ["shame","vergüenza","emotions",null],
  ["guilt","culpa","emotions",null],
  ["gratitude","gratitud","emotions",null],
  ["pride","orgullo","emotions",null],
  ["relief","alivio","emotions",null],
  ["boredom","aburrimiento","emotions",null],
  ["excitement","emoción/entusiasmo","emotions",null],
  ["confusion","confusión","emotions",null],
  ["oval","óvalo","colors_shapes",null],
  ["easily","fácilmente","adverbs",null],
  ["perhaps","quizás/tal vez","adverbs",null],
  ["probably","probablemente","adverbs",null],
  ["certainly","ciertamente/seguro","adverbs",null],
  ["suddenly","de repente/repentinamente","adverbs",null],
  ["finally","finalmente/al fin","adverbs",null],
  ["recently","recientemente","adverbs",null],
  ["immediately","inmediatamente","adverbs",null],
  ["photography","fotografía","arts_culture",null],
  ["sculpture","escultura","arts_culture",null],
  ["literature","literatura","arts_culture",null],
  ["poem","poema","arts_culture",null],
  ["violin","violín","arts_culture",null],
  ["director","director","arts_culture",null],
  ["customer","cliente","shopping",null],
  ["brand","marca","shopping",null],
  ["product","producto","shopping",null],
  ["visa","visa","travel",null],
  ["reservation","reserva/reservación","travel",null],
  ["destination","destino","travel",null],
  ["departure","salida/partida","travel",null],
  ["arrival","llegada","travel",null],
  ["boarding pass","tarjeta de embarque","travel",null],
  ["customs","aduana","travel",null],
  ["currency","moneda/divisa","travel",null],
  ["exchange rate","tipo de cambio","travel",null],
  ["travel insurance","seguro de viaje","travel",null],
  ["salary","salario/sueldo","work_business",null],
  ["career","carrera profesional","work_business",null],
  ["colleague","colega/compañero de trabajo","work_business",null],
  ["interview","entrevista","work_business",null],
  ["resume","currículum","work_business",null],
  ["contract","contrato","work_business",null],
  ["deadline","fecha límite","work_business",null],
  ["project","proyecto","work_business",null],
  ["presentation","presentación","work_business",null],
  ["client","cliente","work_business",null],
  ["manager","gerente/encargado","work_business",null],
  ["employee","empleado","work_business",null],
  ["employer","empleador","work_business",null],
  ["promotion","ascenso/promoción","work_business",null],
  ["retirement","jubilación/retiro","work_business",null],
  ["business","negocio/empresa","work_business",null],
  ["factory","fábrica","work_business",null],
  ["industry","industria","work_business",null],
  ["trade","comercio/intercambio","work_business",null],
  ["profit","ganancia/beneficio","work_business",null],
  ["loss","pérdida","work_business",null],
  ["investment","inversión","work_business",null],
  ["budget","presupuesto","work_business",null],
  ["tax","impuesto","work_business",null],
  ["carry on","continuar","phrasal_verbs",null],
  ["drop by","pasar a visitar brevemente","phrasal_verbs",null],
  ["end up","terminar por","phrasal_verbs",null],
  ["figure out","averiguar","phrasal_verbs",null],
  ["fill in","rellenar un formulario","phrasal_verbs",null],
  ["get along with","llevarse bien con","phrasal_verbs",null],
  ["go ahead","seguir adelante","phrasal_verbs",null],
  ["hold on","esperar un momento","phrasal_verbs",null],
  ["look after","cuidar de","phrasal_verbs",null],
  ["pay back","devolver dinero prestado","phrasal_verbs",null],
  ["pick up","recoger","phrasal_verbs",null],
  ["set up","organizar","phrasal_verbs",null],
  ["show up","aparecer","phrasal_verbs",null],
  ["sort out","resolver un problema","phrasal_verbs",null],
  ["turn down","rechazar","phrasal_verbs",null],
  ["turn out","resultar","phrasal_verbs",null],
  ["work out","hacer ejercicio","phrasal_verbs",null],
  ["break down","averiarse","phrasal_verbs",null],
  ["calm down","calmarse","phrasal_verbs",null],
  ["check in","registrarse al llegar","phrasal_verbs",null],
  ["call it a day","dar por terminado el trabajo","idioms",null],
  ["get the hang of it","aprender a hacerlo bien","idioms",null],
  ["keep an eye on","vigilar de cerca","idioms",null],
  ["under the weather","sentirse indispuesto","idioms",null],
  ["gonna","voy a","social",null],
  ["wanna","quiero","social",null],
  ["gotta","tengo que","social",null],
  ["kinda","algo/más o menos","social",null],
  ["whatever","lo que sea","social",null],
  ["huh","¿eh?","social",null],
  ["sweetie","cariño","social",null],
  ["literally","literalmente","adverbs",null],
  ["basically","básicamente","adverbs",null],
  ["totally","totalmente","adverbs",null],
  ["seriously","en serio","adverbs",null],
  ["honestly","sinceramente","adverbs",null],
  ["anyway","de todos modos","adverbs",null],
  ["definitely","sin duda","adverbs",null],
  ["absolutely","absolutamente","adverbs",null],
  ["obviously","obviamente","adverbs",null],
  ["especially","especialmente","adverbs",null],
  ["simply","simplemente","adverbs",null],
  ["completely","completamente","adverbs",null],
  ["nearly","casi","adverbs",null],
  ["anymore","ya no","adverbs",null],
  ["anywhere","en cualquier lugar","adverbs",null],
  ["nowhere","en ningún lugar","adverbs",null],
  ["however","sin embargo","adverbs",null],
  ["lately","últimamente","adverbs",null],
  ["somehow","de algún modo","adverbs",null],
  ["either","tampoco/cualquiera","adverbs",null],
  ["rather","más bien","adverbs",null],
  ["quite","bastante","adverbs",null],
  ["awkward","incómodo/torpe","adjectives",null],
  ["annoying","molesto","adjectives",null],
  ["rude","grosero","adjectives",null],
  ["polite","educado","adjectives",null],
  ["honest","honesto","adjectives",null],
  ["clever","listo","adjectives",null],
  ["fair","justo","adjectives",null],
  ["gorgeous","precioso","adjectives",null],
  ["tiny","diminuto","adjectives",null],
  ["stuck","atascado","adjectives",null],
  ["broke","sin dinero","adjectives",null],
  ["embarrassed","avergonzado","emotions",null],
  ["bet","apostar","verbs_action",null],
  ["figure","imaginarse/calcular","verbs_action",null],
  ["notice","notar","verbs_action",null],
  ["realize","darse cuenta","verbs_action",null],
  ["suppose","suponer","verbs_action",null],
  ["manage","lograr/arreglárselas","verbs_action",null],
  ["ignore","ignorar","verbs_action",null],
  ["afford","permitirse","verbs_action",null],
  ["forgive","perdonar","verbs_action",null],
  ["blame","culpar","verbs_action",null],
  ["swear","jurar","verbs_action",null],
  ["pretend","fingir","verbs_action",null],
  ["shake","sacudir/temblar","verbs_action",null],
  ["wave","saludar con la mano","verbs_action",null],
  ["beat","vencer/golpear","verbs_action",null],
  ["habit","hábito","other",null],
  ["memory","recuerdo","other",null],
  ["crowd","multitud","other",null],
  ["gossip","chisme","other",null],
  ["mood","estado de ánimo","other",null],
  ["rumor","rumor","other",null],
  ["excuse","excusa","other",null],
  ["argument","discusión","other",null],
  ["fault","culpa","other",null],
  ["give up","rendirse","phrasal_verbs",null],
  ["look for","buscar","phrasal_verbs",null],
  ["look forward to","tener ganas de","phrasal_verbs",null],
  ["get up","levantarse","phrasal_verbs",null],
  ["wake up","despertarse","phrasal_verbs",null],
  ["sit down","sentarse","phrasal_verbs",null],
  ["stand up","ponerse de pie","phrasal_verbs",null],
  ["put on","ponerse","phrasal_verbs",null],
  ["take off","quitarse/despegar","phrasal_verbs",null],
  ["turn on","encender","phrasal_verbs",null],
  ["turn off","apagar","phrasal_verbs",null],
  ["come back","volver","phrasal_verbs",null],
  ["go out","salir","phrasal_verbs",null],
  ["find out","descubrir","phrasal_verbs",null],
  ["run out of","quedarse sin","phrasal_verbs",null],
  ["throw away","tirar","phrasal_verbs",null],
  ["give back","devolver","phrasal_verbs",null],
  ["try on","probarse","phrasal_verbs",null],
  ["slow down","reducir la velocidad","phrasal_verbs",null],
  ["cheer up","animarse","phrasal_verbs",null],
  ["clean up","limpiar","phrasal_verbs",null],
  ["hang out","pasar el rato","phrasal_verbs",null],
  ["move on","seguir adelante","phrasal_verbs",null],
  ["grow up","crecer","phrasal_verbs",null],
  ["take care of","cuidar de","phrasal_verbs",null],
  ["deal with","lidiar con","phrasal_verbs",null],
  ["come over","venir a casa","phrasal_verbs",null],
  ["break the ice","romper el hielo","idioms",null],
  ["piece of cake","pan comido","idioms",null],
  ["break a leg","mucha suerte","idioms",null],
  ["better late than never","más vale tarde que nunca","idioms",null],
  ["crutch","muleta","health",null],
];
