// saflash — B2 words. Row format: [english, spanish, category, subcategory|null]

export const B2_WORDS = [
  ["threaten","amenazar","other",null],
  ["stale","rancio/pasado","adjectives",null],
  ["crutch","muleta","health",null],
  ["bank account","cuenta bancaria","money_banking",null],
  ["current account","cuenta corriente","money_banking",null],
  ["savings account","cuenta de ahorros","money_banking",null],
  ["bank statement","estado de cuenta bancario","money_banking",null],
  ["account balance","saldo de la cuenta","money_banking",null],
  ["bank transfer","transferencia bancaria","money_banking",null],
  ["direct debit","débito automático","money_banking",null],
  ["standing order","orden de pago periódica","money_banking",null],
  ["withdrawal","retiro de dinero","money_banking",null],
  ["deposit","depósito","money_banking",null],
  ["overdraft","sobregiro","money_banking",null],
  ["transaction","transacción","money_banking",null],
  ["transaction fee","comisión por transacción","money_banking",null],
  ["service charge","cargo por servicio","money_banking",null],
  ["interest rate","tasa de interés","money_banking",null],
  ["loan repayment","pago de un préstamo","money_banking",null],
  ["monthly installment","cuota mensual","money_banking",null],
  ["mortgage","hipoteca","money_banking",null],
  ["credit limit","límite de crédito","money_banking",null],
  ["credit score","puntaje crediticio","money_banking",null],
  ["debt","deuda","money_banking",null],
  ["late payment","pago atrasado","money_banking",null],
  ["payment deadline","fecha límite de pago","money_banking",null],
  ["currency conversion","conversión de moneda","money_banking",null],
  ["foreign currency","moneda extranjera","money_banking",null],
  ["cash machine","cajero automático","money_banking",null],
  ["contactless payment","pago sin contacto","money_banking",null],
  ["online banking","banca en línea","money_banking",null],
  ["mobile banking","banca móvil","money_banking",null],
  ["account holder","titular de la cuenta","money_banking",null],
  ["proof of income","comprobante de ingresos","money_banking",null],
  ["bank branch","sucursal bancaria","money_banking",null],
  ["tax return","declaración de impuestos","money_banking",null],
  ["annual income","ingreso anual","money_banking",null],
  ["living expenses","gastos de manutención","money_banking",null],
  ["household budget","presupuesto familiar","money_banking",null],
  ["emergency fund","fondo de emergencia","money_banking",null],
  ["financial advice","asesoramiento financiero","money_banking",null],
  ["insurance premium","prima de seguro","money_banking",null],
  ["refund request","solicitud de reembolso","money_banking",null],

  ["headline","titular de prensa","media_entertainment",null],
  ["breaking news","noticia de última hora","media_entertainment",null],
  ["news coverage","cobertura informativa","media_entertainment",null],
  ["news report","reportaje informativo","media_entertainment",null],
  ["press release","comunicado de prensa","media_entertainment",null],
  ["editorial","editorial","media_entertainment",null],
  ["opinion column","columna de opinión","media_entertainment",null],
  ["feature article","artículo de fondo","media_entertainment",null],
  ["documentary","documental","media_entertainment",null],
  ["broadcast","transmisión","media_entertainment",null],
  ["live stream","transmisión en vivo por internet","media_entertainment",null],
  ["podcast episode","episodio de pódcast","media_entertainment",null],
  ["subscription","suscripción","media_entertainment",null],
  ["subscriber","suscriptor","media_entertainment",null],
  ["audience","público","media_entertainment",null],
  ["viewership","audiencia de televisión","media_entertainment",null],
  ["ratings","índices de audiencia","media_entertainment",null],
  ["trailer","tráiler","media_entertainment",null],
  ["release date","fecha de estreno","media_entertainment",null],
  ["premiere","estreno","media_entertainment",null],
  ["screening","proyección","media_entertainment",null],
  ["film festival","festival de cine","media_entertainment",null],
  ["soundtrack","banda sonora","media_entertainment",null],
  ["plot twist","giro de la trama","media_entertainment",null],
  ["storyline","trama","media_entertainment",null],
  ["cast","reparto de actores","media_entertainment",null],
  ["lead role","papel protagónico","media_entertainment",null],
  ["supporting actor","actor de reparto","media_entertainment",null],
  ["subtitles","subtítulos","media_entertainment",null],
  ["voice-over","voz en off","media_entertainment",null],
  ["special effects","efectos especiales","media_entertainment",null],
  ["behind the scenes","detrás de cámaras","media_entertainment",null],
  ["sequel","secuela","media_entertainment",null],
  ["remake","nueva versión de una obra","media_entertainment",null],
  ["review","reseña","media_entertainment",null],
  ["critic","crítico","media_entertainment",null],
  ["spoiler","revelación de la trama","media_entertainment",null],
  ["box office","taquilla","media_entertainment",null],
  ["streaming service","servicio de transmisión en línea","media_entertainment",null],
  ["public broadcaster","emisora pública","media_entertainment",null],

  ["climate change","cambio climático","environment",null],
  ["global warming","calentamiento global","environment",null],
  ["greenhouse gas","gas de efecto invernadero","environment",null],
  ["carbon footprint","huella de carbono","environment",null],
  ["carbon emissions","emisiones de carbono","environment",null],
  ["fossil fuel","combustible fósil","environment",null],
  ["renewable energy","energía renovable","environment",null],
  ["solar power","energía solar","environment",null],
  ["wind power","energía eólica","environment",null],
  ["energy efficiency","eficiencia energética","environment",null],
  ["air pollution","contaminación del aire","environment",null],
  ["water pollution","contaminación del agua","environment",null],
  ["plastic waste","residuos plásticos","environment",null],
  ["landfill","vertedero","environment",null],
  ["recycling plant","planta de reciclaje","environment",null],
  ["compost","abono orgánico","environment",null],
  ["organic waste","residuos orgánicos","environment",null],
  ["single-use plastic","plástico de un solo uso","environment",null],
  ["wildlife","vida silvestre","environment",null],
  ["endangered species","especie en peligro de extinción","environment",null],
  ["habitat","hábitat","environment",null],
  ["biodiversity","biodiversidad","environment",null],
  ["conservation","conservación","environment",null],
  ["protected area","área protegida","environment",null],
  ["deforestation","deforestación","environment",null],
  ["reforestation","reforestación","environment",null],
  ["soil erosion","erosión del suelo","environment",null],
  ["drought","sequía","environment",null],
  ["flooding","inundaciones","environment",null],
  ["heatwave","ola de calor","environment",null],
  ["sea level","nivel del mar","environment",null],
  ["fresh water","agua dulce","environment",null],
  ["water shortage","escasez de agua","environment",null],
  ["natural resources","recursos naturales","environment",null],
  ["sustainable farming","agricultura sostenible","environment",null],
  ["environmental impact","impacto ambiental","environment",null],
  ["public transport","transporte público","environment",null],
  ["electric vehicle","vehículo eléctrico","environment",null],
  ["oil spill","derrame de petróleo","environment",null],
  ["ecosystem","ecosistema","environment",null],

  ["research","investigación","science",null],
  ["scientific study","estudio científico","science",null],
  ["hypothesis","hipótesis","science",null],
  ["experiment","experimento","science",null],
  ["observation","observación","science",null],
  ["evidence","pruebas","science",null],
  ["data analysis","análisis de datos","science",null],
  ["research findings","resultados de la investigación","science",null],
  ["conclusion","conclusión","science",null],
  ["theory","teoría","science",null],
  ["scientific method","método científico","science",null],
  ["lab equipment","equipo de laboratorio","science",null],
  ["sample","muestra","science",null],
  ["measurement","medición","science",null],
  ["accuracy","precisión","science",null],
  ["variable","variable","science",null],
  ["control group","grupo de control","science",null],
  ["clinical trial","ensayo clínico","science",null],
  ["side effect","efecto secundario","science",null],
  ["vaccination","vacunación","science",null],
  ["antibiotic","antibiótico","science",null],
  ["bacteria","bacterias","science",null],
  ["pathogen","patógeno","science",null],
  ["immune system","sistema inmunitario","science",null],
  ["genetics","genética","science",null],
  ["DNA","ADN","science",null],
  ["cell","célula","science",null],
  ["molecule","molécula","science",null],
  ["chemical reaction","reacción química","science",null],
  ["chemical element","elemento químico","science",null],
  ["gravity","gravedad","science",null],
  ["electricity","electricidad","science",null],
  ["radiation","radiación","science",null],
  ["temperature","temperatura","science",null],
  ["microscope","microscopio","science",null],
  ["telescope","telescopio","science",null],
  ["satellite","satélite","science",null],
  ["space exploration","exploración espacial","science",null],
  ["discovery","descubrimiento","science",null],
  ["scientific breakthrough","avance científico importante","science",null],

  ["get-together","reunión informal","social",null],
  ["dinner party","cena con invitados","social",null],
  ["housewarming party","fiesta de inauguración de casa","social",null],
  ["family gathering","reunión familiar","social",null],
  ["reunion","reencuentro","social",null],
  ["catch-up","charla para ponerse al día","social",null],
  ["small talk","conversación informal","social",null],
  ["icebreaker","actividad para romper el hielo","social",null],
  ["introduction","presentación entre personas","social",null],
  ["first impression","primera impresión","social",null],
  ["mutual friend","amigo en común","social",null],
  ["acquaintance","conocido","social",null],
  ["close friend","amigo cercano","social",null],
  ["social circle","círculo social","social",null],
  ["guest list","lista de invitados","social",null],
  ["invitation","invitación","social",null],
  ["RSVP","confirmación de asistencia","social",null],
  ["plus-one","acompañante invitado","social",null],
  ["host","anfitrión","social",null],
  ["guest","invitado","social",null],
  ["compliment","cumplido","social",null],
  ["apology","disculpa","social",null],
  ["misunderstanding","malentendido","social",null],
  ["awkward silence","silencio incómodo","social",null],
  ["inside joke","broma que solo entiende un grupo","social",null],
  ["sense of humor","sentido del humor","social",null],
  ["common interest","interés en común","social",null],
  ["shared experience","experiencia compartida","social",null],
  ["conversation starter","tema para iniciar una conversación","social",null],
  ["body language","lenguaje corporal","social",null],
  ["eye contact","contacto visual","social",null],
  ["personal space","espacio personal","social",null],
  ["boundaries","límites personales","social",null],
  ["peer pressure","presión de los compañeros","social",null],
  ["mutual trust","confianza mutua","social",null],
  ["respect","respeto","social",null],
  ["reconciliation","reconciliación","social",null],
  ["friendship","amistad","social",null],
  ["relationship","relación","social",null],
  ["community event","evento comunitario","social",null],

  ["apparently","al parecer","adverbs",null],
  ["presumably","presumiblemente","adverbs",null],
  ["supposedly","supuestamente","adverbs",null],
  ["arguably","podría decirse que","adverbs",null],
  ["undoubtedly","sin duda","adverbs",null],
  ["inevitably","inevitablemente","adverbs",null],
  ["eventually","con el tiempo","adverbs",null],
  ["gradually","gradualmente","adverbs",null],
  ["steadily","de manera constante","adverbs",null],
  ["rapidly","rápidamente","adverbs",null],
  ["briefly","brevemente","adverbs",null],
  ["frequently","con frecuencia","adverbs",null],
  ["occasionally","de vez en cuando","adverbs",null],
  ["rarely","rara vez","adverbs",null],
  ["hardly","apenas","adverbs",null],
  ["barely","por muy poco","adverbs",null],
  ["roughly","aproximadamente","adverbs",null],
  ["approximately","aproximadamente","adverbs",null],
  ["precisely","con precisión","adverbs",null],
  ["relatively","relativamente","adverbs",null],
  ["particularly","particularmente","adverbs",null],
  ["significantly","considerablemente","adverbs",null],
  ["considerably","considerablemente","adverbs",null],
  ["slightly","ligeramente","adverbs",null],
  ["entirely","por completo","adverbs",null],
  ["partially","parcialmente","adverbs",null],
  ["otherwise","de lo contrario","adverbs",null],
  ["meanwhile","mientras tanto","adverbs",null],
  ["consequently","en consecuencia","adverbs",null],
  ["nevertheless","sin embargo","adverbs",null],
  ["furthermore","además","adverbs",null],
  ["likewise","del mismo modo","adverbs",null],
  ["instead","en su lugar","adverbs",null],
  ["accordingly","según corresponda","adverbs",null],
  ["deliberately","a propósito","adverbs",null],
  ["accidentally","por accidente","adverbs",null],
  ["independently","de manera independiente","adverbs",null],
  ["effectively","de manera eficaz","adverbs",null],
  ["openly","abiertamente","adverbs",null],
  ["privately","en privado","adverbs",null],

  ["bring up","mencionar un tema","phrasal_verbs",null],
  ["carry on","continuar","phrasal_verbs",null],
  ["come across","encontrar por casualidad","phrasal_verbs",null],
  ["come up with","idear","phrasal_verbs",null],
  ["cut down on","reducir el consumo de","phrasal_verbs",null],
  ["drop by","pasar a visitar brevemente","phrasal_verbs",null],
  ["end up","terminar por","phrasal_verbs",null],
  ["fall behind","quedarse atrás","phrasal_verbs",null],
  ["figure out","averiguar","phrasal_verbs",null],
  ["fill in","rellenar un formulario","phrasal_verbs",null],
  ["get along with","llevarse bien con","phrasal_verbs",null],
  ["get away with","salirse con la suya","phrasal_verbs",null],
  ["get over","superar","phrasal_verbs",null],
  ["give in","ceder","phrasal_verbs",null],
  ["go ahead","seguir adelante","phrasal_verbs",null],
  ["grow out of","dejar atrás una costumbre al crecer","phrasal_verbs",null],
  ["hold on","esperar un momento","phrasal_verbs",null],
  ["keep up with","mantener el ritmo de","phrasal_verbs",null],
  ["look after","cuidar de","phrasal_verbs",null],
  ["look into","investigar","phrasal_verbs",null],
  ["make up for","compensar","phrasal_verbs",null],
  ["pass out","desmayarse","phrasal_verbs",null],
  ["pay back","devolver dinero prestado","phrasal_verbs",null],
  ["pick up","recoger","phrasal_verbs",null],
  ["point out","señalar","phrasal_verbs",null],
  ["put off","aplazar","phrasal_verbs",null],
  ["put up with","soportar","phrasal_verbs",null],
  ["run into","encontrarse con alguien por casualidad","phrasal_verbs",null],
  ["set up","organizar","phrasal_verbs",null],
  ["show up","aparecer","phrasal_verbs",null],
  ["sort out","resolver un problema","phrasal_verbs",null],
  ["take after","parecerse a un familiar","phrasal_verbs",null],
  ["take over","hacerse cargo de","phrasal_verbs",null],
  ["turn down","rechazar","phrasal_verbs",null],
  ["turn out","resultar","phrasal_verbs",null],
  ["work out","hacer ejercicio","phrasal_verbs",null],
  ["back up","hacer una copia de seguridad","phrasal_verbs",null],
  ["break down","averiarse","phrasal_verbs",null],
  ["calm down","calmarse","phrasal_verbs",null],
  ["check in","registrarse al llegar","phrasal_verbs",null],
];
