// saflash — C1 words. Row format: [english, spanish, category, subcategory|null]

export const C1_WORDS = [
  ["stakeholder","parte interesada","work_business",null],
  ["shareholder","accionista","work_business",null],
  ["board of directors","junta directiva","work_business",null],
  ["chief executive","director ejecutivo","work_business",null],
  ["senior management","alta dirección","work_business",null],
  ["middle management","mandos intermedios","work_business",null],
  ["workforce","plantilla de trabajadores","work_business",null],
  ["recruitment","contratación de personal","work_business",null],
  ["staff turnover","rotación de personal","work_business",null],
  ["employee retention","retención de empleados","work_business",null],
  ["career progression","progreso profesional","work_business",null],
  ["performance review","evaluación del desempeño","work_business",null],
  ["pay rise","aumento de sueldo","work_business",null],
  ["severance pay","indemnización por despido","work_business",null],
  ["redundancy","despido por reducción de personal","work_business",null],
  ["collective bargaining","negociación colectiva","work_business",null],
  ["trade union","sindicato","work_business",null],
  ["workplace culture","cultura laboral","work_business",null],
  ["conflict of interest","conflicto de intereses","work_business",null],
  ["due diligence","diligencia debida","work_business",null],
  ["merger","fusión de empresas","work_business",null],
  ["acquisition","adquisición de una empresa","work_business",null],
  ["market share","cuota de mercado","work_business",null],
  ["competitive advantage","ventaja competitiva","work_business",null],
  ["profit margin","margen de beneficio","work_business",null],
  ["cash flow","flujo de caja","work_business",null],
  ["revenue stream","fuente de ingresos","work_business",null],
  ["operating costs","costos operativos","work_business",null],
  ["overhead costs","gastos generales","work_business",null],
  ["financial forecast","previsión financiera","work_business",null],
  ["quarterly earnings","beneficios trimestrales","work_business",null],
  ["return on investment","rentabilidad de la inversión","work_business",null],
  ["supply chain","cadena de suministro","work_business",null],
  ["inventory management","gestión de inventario","work_business",null],
  ["quality assurance","garantía de calidad","work_business",null],
  ["product launch","lanzamiento de un producto","work_business",null],
  ["target market","mercado objetivo","work_business",null],
  ["brand awareness","reconocimiento de marca","work_business",null],
  ["customer loyalty","fidelidad de los clientes","work_business",null],
  ["business proposal","propuesta comercial","work_business",null],
  ["legislation","legislación","law_government",null],
  ["bill","proyecto de ley","law_government",null],
  ["amendment","enmienda","law_government",null],
  ["regulation","normativa","law_government",null],
  ["legal framework","marco jurídico","law_government",null],
  ["constitutional right","derecho constitucional","law_government",null],
  ["civil rights","derechos civiles","law_government",null],
  ["human rights","derechos humanos","law_government",null],
  ["freedom of speech","libertad de expresión","law_government",null],
  ["rule of law","estado de derecho","law_government",null],
  ["separation of powers","separación de poderes","law_government",null],
  ["judiciary","poder judicial","law_government",null],
  ["parliamentary debate","debate parlamentario","law_government",null],
  ["public policy","política pública","law_government",null],
  ["local authority","autoridad local","law_government",null],
  ["civil servant","funcionario público","law_government",null],
  ["elected official","funcionario electo","law_government",null],
  ["general election","elecciones generales","law_government",null],
  ["voter turnout","participación electoral","law_government",null],
  ["ballot paper","papeleta de votación","law_government",null],
  ["constituency","distrito electoral","law_government",null],
  ["opposition party","partido de oposición","law_government",null],
  ["coalition government","gobierno de coalición","law_government",null],
  ["public consultation","consulta pública","law_government",null],
  ["court ruling","sentencia judicial","law_government",null],
  ["legal proceedings","proceso judicial","law_government",null],
  ["lawsuit","demanda judicial","law_government",null],
  ["plaintiff","demandante","law_government",null],
  ["defendant","demandado o acusado","law_government",null],
  ["testimony","testimonio","law_government",null],
  ["witness statement","declaración de un testigo","law_government",null],
  ["burden of proof","carga de la prueba","law_government",null],
  ["presumption of innocence","presunción de inocencia","law_government",null],
  ["legal aid","asistencia jurídica gratuita","law_government",null],
  ["appeal","apelación","law_government",null],
  ["fine","multa","law_government",null],
  ["community service","servicio comunitario","law_government",null],
  ["privacy law","ley de protección de la privacidad","law_government",null],
  ["consumer protection","protección del consumidor","law_government",null],
  ["whistleblower","denunciante de irregularidades","law_government",null],
  ["peer review","revisión por pares","science",null],
  ["research paper","artículo de investigación","science",null],
  ["scientific consensus","consenso científico","science",null],
  ["reproducibility","reproducibilidad","science",null],
  ["replication study","estudio de replicación","science",null],
  ["data set","conjunto de datos","science",null],
  ["data collection","recopilación de datos","science",null],
  ["statistical significance","significación estadística","science",null],
  ["correlation","correlación","science",null],
  ["causation","causalidad","science",null],
  ["bias","sesgo","science",null],
  ["margin of error","margen de error","science",null],
  ["random sample","muestra aleatoria","science",null],
  ["sample size","tamaño de la muestra","science",null],
  ["placebo","placebo","science",null],
  ["double-blind study","estudio de doble ciego","science",null],
  ["longitudinal study","estudio longitudinal","science",null],
  ["case study","estudio de caso","science",null],
  ["ethical approval","aprobación ética","science",null],
  ["informed consent","consentimiento informado","science",null],
  ["gene expression","expresión génica","science",null],
  ["genetic mutation","mutación genética","science",null],
  ["genome","genoma","science",null],
  ["stem cell","célula madre","science",null],
  ["neural network","red neuronal","science",null],
  ["brain imaging","obtención de imágenes cerebrales","science",null],
  ["drug resistance","resistencia a los medicamentos","science",null],
  ["disease outbreak","brote de enfermedad","science",null],
  ["transmission rate","tasa de transmisión","science",null],
  ["diagnostic test","prueba diagnóstica","science",null],
  ["treatment outcome","resultado del tratamiento","science",null],
  ["environmental monitoring","vigilancia ambiental","science",null],
  ["climate model","modelo climático","science",null],
  ["carbon dating","datación por carbono","science",null],
  ["particle accelerator","acelerador de partículas","science",null],
  ["quantum physics","física cuántica","science",null],
  ["artificial intelligence","inteligencia artificial","science",null],
  ["machine learning","aprendizaje automático","science",null],
  ["computational model","modelo computacional","science",null],
  ["technological innovation","innovación tecnológica","science",null],
  ["cultural heritage","patrimonio cultural","arts_culture",null],
  ["intangible heritage","patrimonio inmaterial","arts_culture",null],
  ["cultural identity","identidad cultural","arts_culture",null],
  ["oral tradition","tradición oral","arts_culture",null],
  ["folk art","arte popular","arts_culture",null],
  ["traditional craft","artesanía tradicional","arts_culture",null],
  ["contemporary art","arte contemporáneo","arts_culture",null],
  ["abstract art","arte abstracto","arts_culture",null],
  ["installation art","arte de instalación","arts_culture",null],
  ["public art","arte público","arts_culture",null],
  ["street art","arte urbano","arts_culture",null],
  ["art exhibition","exposición de arte","arts_culture",null],
  ["curator","comisario de exposiciones","arts_culture",null],
  ["art collection","colección de arte","arts_culture",null],
  ["art restoration","restauración de obras de arte","arts_culture",null],
  ["masterpiece","obra maestra","arts_culture",null],
  ["artistic expression","expresión artística","arts_culture",null],
  ["creative process","proceso creativo","arts_culture",null],
  ["artistic influence","influencia artística","arts_culture",null],
  ["aesthetic appeal","atractivo estético","arts_culture",null],
  ["visual arts","artes visuales","arts_culture",null],
  ["performing arts","artes escénicas","arts_culture",null],
  ["live performance","actuación en vivo","arts_culture",null],
  ["stage production","producción teatral","arts_culture",null],
  ["theatre company","compañía de teatro","arts_culture",null],
  ["rehearsal","ensayo de una actuación","arts_culture",null],
  ["choreography","coreografía","arts_culture",null],
  ["musical composition","composición musical","arts_culture",null],
  ["improvisation","improvisación","arts_culture",null],
  ["literary fiction","ficción literaria","arts_culture",null],
  ["narrative voice","voz narrativa","arts_culture",null],
  ["literary criticism","crítica literaria","arts_culture",null],
  ["adaptation","adaptación de una obra","arts_culture",null],
  ["historical context","contexto histórico","arts_culture",null],
  ["cultural exchange","intercambio cultural","arts_culture",null],
  ["representation","representación de un grupo","arts_culture",null],
  ["creative freedom","libertad creativa","arts_culture",null],
  ["artistic legacy","legado artístico","arts_culture",null],
  ["cultural landmark","lugar de importancia cultural","arts_culture",null],
  ["museum exhibit","pieza expuesta en un museo","arts_culture",null],
  ["a blessing in disguise","algo malo que resultó beneficioso","idioms",null],
  ["a drop in the ocean","una cantidad insignificante","idioms",null],
  ["a fine line","una diferencia muy sutil","idioms",null],
  ["a long shot","algo con pocas probabilidades de éxito","idioms",null],
  ["a mixed blessing","algo con ventajas y desventajas","idioms",null],
  ["a slippery slope","un camino que puede llevar a consecuencias cada vez peores","idioms",null],
  ["beat around the bush","andarse con rodeos","idioms",null],
  ["bend over backwards","hacer todo lo posible por ayudar","idioms",null],
  ["burn the midnight oil","trabajar hasta muy tarde","idioms",null],
  ["by the skin of your teeth","por un margen muy pequeño","idioms",null],
  ["cut corners","hacer algo de forma descuidada para ahorrar tiempo o dinero","idioms",null],
  ["draw the line","poner un límite","idioms",null],
  ["give someone the benefit of the doubt","concederle a alguien el beneficio de la duda","idioms",null],
  ["go the extra mile","hacer un esfuerzo adicional","idioms",null],
  ["hit the nail on the head","dar en el clavo","idioms",null],
  ["let the cat out of the bag","revelar un secreto sin querer","idioms",null],
  ["pull strings","mover influencias","idioms",null],
  ["put all your eggs in one basket","apostarlo todo a una sola opción","idioms",null],
  ["read between the lines","leer entre líneas","idioms",null],
  ["sit on the fence","evitar tomar partido","idioms",null],
  ["take it with a grain of salt","tomarlo con escepticismo","idioms",null],
  ["the tip of the iceberg","solo una pequeña parte del problema","idioms",null],
  ["think outside the box","pensar de manera creativa","idioms",null],
  ["throw in the towel","darse por vencido","idioms",null],
  ["ambiguous","ambiguo","adjectives",null],
  ["compelling","convincente","adjectives",null],
  ["convoluted","enrevesado","adjectives",null],
  ["credible","creíble","adjectives",null],
  ["deceptive","engañoso","adjectives",null],
  ["deliberate","intencionado","adjectives",null],
  ["detrimental","perjudicial","adjectives",null],
  ["discreet","discreto","adjectives",null],
  ["distinctive","distintivo","adjectives",null],
  ["dubious","dudoso","adjectives",null],
  ["elusive","difícil de encontrar o comprender","adjectives",null],
  ["emphatic","enfático","adjectives",null],
  ["feasible","viable","adjectives",null],
  ["flawed","defectuoso","adjectives",null],
  ["forthcoming","próximo a ocurrir","adjectives",null],
  ["frank","sincero y directo","adjectives",null],
  ["genuine","auténtico","adjectives",null],
  ["impartial","imparcial","adjectives",null],
  ["inherent","inherente","adjectives",null],
  ["insightful","perspicaz","adjectives",null],
  ["intricate","complejo y detallado","adjectives",null],
  ["meticulous","meticuloso","adjectives",null],
  ["misleading","que induce a error","adjectives",null],
  ["nuanced","lleno de matices","adjectives",null],
  ["plausible","verosímil","adjectives",null],
  ["prominent","destacado","adjectives",null],
  ["questionable","cuestionable","adjectives",null],
  ["resilient","capaz de recuperarse de las dificultades","adjectives",null],
  ["rigorous","riguroso","adjectives",null],
  ["scarce","escaso","adjectives",null],
  ["skeptical","escéptico","adjectives",null],
  ["subtle","sutil","adjectives",null],
  ["substantial","considerable","adjectives",null],
  ["sustainable","sostenible","adjectives",null],
  ["tentative","provisional o poco seguro","adjectives",null],
  ["thorough","minucioso","adjectives",null],
  ["unprecedented","sin precedentes","adjectives",null],
  ["viable","factible","adjectives",null],
  ["widespread","generalizado","adjectives",null],
  ["worthwhile","que vale la pena","adjectives",null],
  ["the elephant in the room","el tema incómodo que nadie menciona","idioms",null],
  ["turn a blind eye","hacer la vista gorda","idioms",null],
  ["get cold feet","echarse atrás por miedo","idioms",null],
  ["add insult to injury","echar sal en la herida","idioms",null],
  ["the last straw","la gota que colmó el vaso","idioms",null],
  ["bark up the wrong tree","buscar en el lugar equivocado","idioms",null],
  ["steal the show","llevarse todos los aplausos","idioms",null],
  ["go back to the drawing board","volver a empezar","idioms",null],
  ["wrap your head around","llegar a entender","idioms",null],
  ["a double-edged sword","un arma de doble filo","idioms",null],
  ["cut to the chase","ir al grano","idioms",null],
  ["leave no stone unturned","no dejar piedra sin remover","idioms",null],
  ["stand your ground","mantenerse firme","idioms",null],
  ["the best of both worlds","lo mejor de ambos mundos","idioms",null],
  ["cross that bridge when you come to it","ya veremos cuando llegue el momento","idioms",null],
  ["have a chip on your shoulder","guardar rencor","idioms",null],
];
