// saflash — Builds src/seeds/corpus.mjs: real frequency and one example
// sentence (with Spanish translation) for every seed word.
//
// Sources, downloaded into <data-dir> first (bunzip2 the Tatoeba files):
//   en_50k.txt          FrequencyWords, OpenSubtitles 2018 (Hermit Dave, CC BY-SA 4.0)
//     https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/en/en_50k.txt
//   eng_sentences.tsv   Tatoeba per-language exports (CC BY 2.0 FR)
//   spa_sentences.tsv     https://downloads.tatoeba.org/exports/per_language/eng/eng_sentences.tsv.bz2
//   eng-spa_links.tsv     .../spa/spa_sentences.tsv.bz2, .../eng/eng-spa_links.tsv.bz2
//
// Usage: node scripts/build-corpus.mjs <data-dir>
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { WORDS_COMPACT_BY_LEVEL } from '../src/seeds/words/index.mjs';

const dir = process.argv[2];
if (!dir) {
  console.error('Usage: node scripts/build-corpus.mjs <data-dir>');
  process.exit(1);
}

const lines = file => readFileSync(join(dir, file), 'utf8').split('\n').filter(Boolean);
const tokens = text => text.toLowerCase().match(/[a-z]+(?:'[a-z]+)?/g) || [];
const UNKNOWN = 60000;

// ── Frequency: rank and occurrences per million words of subtitles ──
const rank = new Map();
const counts = new Map();
let total = 0;
lines('en_50k.txt').forEach((line, i) => {
  const [word, count] = line.split(' ');
  rank.set(word, i + 1);
  counts.set(word, Number(count));
  total += Number(count);
});

// Multi-word items take the rank of their rarest word.
function wordRank(text) {
  return Math.max(...tokens(text).map(t => rank.get(t) ?? UNKNOWN));
}

function perMillion(text) {
  const parts = tokens(text);
  if (parts.length !== 1) return 0;
  return Math.round(((counts.get(parts[0]) || 0) / total) * 1e6 * 100) / 100;
}

// ── Tatoeba: English sentences that have a Spanish translation ──
const links = new Map(); // eng id -> spa ids
for (const line of lines('eng-spa_links.tsv')) {
  const [eng, spa] = line.split('\t');
  if (!links.has(eng)) links.set(eng, []);
  links.get(eng).push(spa);
}
const spaIds = new Set([...links.values()].flat());
const spanish = new Map();
for (const line of lines('spa_sentences.tsv')) {
  const [id, , text] = line.split('\t');
  if (spaIds.has(id)) spanish.set(id, text);
}

const sentences = []; // { en, es, words }
const index = new Map(); // token -> sentence indexes
for (const line of lines('eng_sentences.tsv')) {
  const [id, , en] = line.split('\t');
  if (!links.has(id)) continue;
  const words = tokens(en);
  if (words.length < 3 || words.length > 10) continue;
  const es = links.get(id).map(s => spanish.get(s)).filter(Boolean).sort((a, b) => a.length - b.length)[0];
  if (!es) continue;
  const at = sentences.push({ en, es, words }) - 1;
  for (const w of new Set(words)) {
    if (!index.has(w)) index.set(w, []);
    index.get(w).push(at);
  }
}

// Best example: contains the item exactly once and every other word is as
// common as possible (one new thing per sentence), then the shortest.
function bestExample(item) {
  const target = tokens(item);
  if (!target.length) return null;
  // The exact item (so a cloze can blank it), any case.
  const escaped = item.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g, '\\$&').replace(/ /g, '\\s+');
  const pattern = new RegExp(`(^|[^a-z'])${escaped}(?![a-z'])`, 'g');
  let best = null;
  for (const at of index.get(target[0]) || []) {
    const s = sentences[at];
    const lower = s.en.toLowerCase();
    if ((lower.match(pattern) || []).length !== 1) continue;
    const others = s.words.filter(w => !target.includes(w));
    const hardest = Math.max(0, ...others.map(w => rank.get(w) ?? UNKNOWN));
    const score = hardest * 100 + s.words.length;
    if (!best || score < best.score) best = { score, en: s.en, es: s.es };
  }
  return best && [best.en, best.es];
}

const corpus = {};
let withExample = 0;
for (const rows of Object.values(WORDS_COMPACT_BY_LEVEL)) {
  for (const [english] of rows) {
    const example = bestExample(english);
    if (example) withExample += 1;
    corpus[english.toLowerCase()] = [wordRank(english), perMillion(english), ...(example || [])];
  }
}

const body = Object.entries(corpus)
  .map(([word, data]) => `  ${JSON.stringify(word)}: ${JSON.stringify(data)},`)
  .join('\n');
writeFileSync(
  new URL('../src/seeds/corpus.mjs', import.meta.url),
  `// saflash — Generated by scripts/build-corpus.mjs. Do not edit by hand.
// word: [subtitle frequency rank, occurrences per million words, example EN, example ES]
// Frequency: FrequencyWords (OpenSubtitles 2018) by Hermit Dave, CC BY-SA 4.0.
// Examples: Tatoeba (tatoeba.org), CC BY 2.0 FR.
export const CORPUS = {
${body}
};
`
);
console.log(`${Object.keys(corpus).length} words, ${withExample} with examples, ${sentences.length} candidate sentences`);
